Entry.create! name: 'Martin'
Entry.create! name: 'cruger'
Entry.create! name: 'Hanz'
Entry.create! name: 'Tom'
Entry.create! name: 'Rafael'
Entry.create! name: 'Ermungang'
Entry.create! name: 'Asmmund'